config/routes.rb
Backchannel::Application.routes.draw do

  devise_for :users
  resources :administrators
  resources :reply_votes
  resources :replies
  resources :post_votes
  resources :posts
  resources :users

  devise_for :users do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_out", :to => "devise/sessions#destroy"
  end

  match 'posts/vote/:id', :to => 'posts#vote'
  match 'search', :to => 'posts#search'

  resources :administrators do
    member do
      get 'change_admin'
    end
  end

  resources :replies do
    member do
      get 'add_reply'
    end
  end

  match ':controller(/:id(/:action))'
  match ':controller/:action/:id'

  root :to => 'posts#index'

end

app/models/reply.rb
class Reply < ActiveRecord::Base

  attr_accessible  :user_id, :reply_text, :reply_votes, :post_id, :vote_count
  belongs_to :user
  belongs_to :post
  has_many :reply_votes, :dependent => :destroy

  #validates_presence_of :user_id, :message => I18n.t('AuthenticatedUser')

  def self.search(search)
    #search_condition = "%" + search + "%"
    #self.find(:all, :conditions => ['reply_text LIKE ?', search_condition])
    if !search.nil?
      search_length = search.split.length
      return find(:all, :conditions => ['reply_text LIKE ? AND reply_text LIKE ? AND reply_text LIKE ?',
        "%#{search.split[0]}%", "%#{search.split[1]}%", "%#{search.split[search_length]}%" ])
    else
      find(:all)
    end
  end

  has_many :reply_votes, :dependent => :destroy
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  # GET /replies
  # GET /replies.json
  def index
    @replies = Reply.all
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @replies }
    end
  end

  # GET /replies/1
  # GET /replies/1.json
  def show
    if (params[:id] == 'search')
      @posts = Post.search( params[:q] )
      @replies = Reply.search( params[:q] )
      @user = User.search( params[:q] )
      @userPost = Array.new
      unless @user.nil?
        @user.each do |users|
          @userPost << Post.find_by_user_id(users.id)
        end
      end
      render 'posts/search' and return
    end
    #@reply = Reply.find(params[:id])
    #@reply2 = Reply.where(:post_id => params[:id])
    @post = Post.find(params[:id])
    @reply = Reply.find_by_sql ["select * from replies where post_id = ?", params[:id]]
    @reply.sort! { |a,b| b.vote_count <=> a.vote_count }
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reply }
    end
  end

  # GET /replies/new
  # GET /replies/new.json
  def new
    @reply = Reply.new
    session[:post_id] = params[:id]
    #@reply.post_id = params[:id]
    #@reply.user_id = current_user.id
    #@reply.post_id = params[:id].to_i
    #@reply.vote_count = 1
    #@post = Post.find(params[:id])
    #@reply.post_id = params[:id].to_i
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reply }
    end
  end

  # GET /replies/1/edit
  def edit
    @reply = Reply.find(params[:id])
    if current_user.id != @reply.user_id
      redirect_to posts_path, alert:  'You may only edit your own replies.'
    end
  end

  # POST /replies
  # POST /replies.json
  def create
    @reply = Reply.new(params[:reply])
    @reply.user_id = current_user.id
    @reply.post_id = session[:post_id]
    @reply.vote_count = 0
    respond_to do |format|
      if @reply.save
        format.html { redirect_to reply_path(@reply.post_id), notice: 'Reply was successfully created.' }
        format.json { render json: @reply, status: :created, location: @reply }
      else
        format.html { render action: "new" }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /replies/1
  # PUT /replies/1.json
  def update
    @reply = Reply.find(params[:id])

    respond_to do |format|
      if @reply.update_attributes(params[:reply])
        format.html { redirect_to reply_path(@reply.post_id), notice: 'Reply was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    @reply = Reply.find(params[:id])
    @post = Post.find(@reply.post_id)
    @reply.destroy

    respond_to do |format|
      format.html { redirect_to reply_path(@post.id) }
      format.json { head :ok }
    end
  end

  def add_reply

  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
<%= form_for(@reply) do |f| %>
  <% if @reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
      <% @reply.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :reply_text %><br />
    <%= f.text_area :reply_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/replies/edit.html.erb
<h1>Editing reply</h1>

<%= render 'form' %>

<%= link_to 'Show', @reply %> |
<%= link_to 'Back', posts_path %>

app/views/replies/index.html.erb
<h1>Listing replies</h1>

<table>
  <tr>
    <th>Reply text</th>
    <th>Vote count</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @replies.each do |reply| %>
  <tr>
    <td><%= reply.reply_text %></td>
    <td><%= reply.vote_count %></td>
    <td><%= link_to 'Show', reply %></td>
    <% unless !current_user.id == reply.user_id %>
        <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
    <% end %>
    <td><%= link_to 'Destroy', reply, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/new.html.erb
<h1>New reply</h1>

<%= render 'form' %>

<%= link_to 'Back', reply_path(session[:post_id]) %>

app/views/replies/show.html.erb
<h2>Original Post #<%= @post.id %> submitted by <%= User.find(@post.user_id).user_code %></h2>

<table id="table-style">
  <thead>
  <tr>
    <th>Author:</th>
    <th>Post Text:</th>
  </tr>
    </thead>
  <tr>
    <td><%= User.find(@post.user_id).user_code %></td>
    <td><%= @post.post_text %></td>
  </tr>
</table>
<h2>Replies</h2>
<table id="table-style">
    <thead>
    <tr>
    <th>Reply text</th>
    <th>Reply Vote Count</th>
  </tr>
  </thead>
  <% unless @reply.size == 0 %>
    <% @reply.each do |replies| %>
        <tr>
        <td><%= replies.reply_text %></td>
        <td><%= replies.vote_count %></td>
        <% unless !user_signed_in? %>
            <% unless !current_user.id == replies.user_id %>
                <td><%= link_to 'Edit', edit_reply_path(replies) %></td>
            <% end %>
            <% unless current_user.id == replies.user_id %>
               <td><%= link_to 'Vote', new_reply_vote_path(replies) %></td>
            <% end %>
            <% unless !current_user.is_admin? %>
              <td><%= link_to 'Destroy', replies.id.to_s + '/destroy' , confirm: 'Are you sure?', :method => :delete %></td>
            <% end %>
         <% end %>
        </tr>|
    <% end %>
  <% end %>
</table>
<%= link_to 'Back to Posts', posts_path %>
<% unless !user_signed_in? %>
    <%= link_to 'Add a Reply', new_reply_path(:id => params[:id]) %>
<% end %>