config/routes.rb
Backchannel::Application.routes.draw do

  devise_for :users
  resources :administrators
  resources :reply_votes
  resources :replies
  resources :post_votes
  resources :posts
  resources :users

  devise_for :users do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_out", :to => "devise/sessions#destroy"
  end

  match 'posts/vote/:id', :to => 'posts#vote'
  match 'search', :to => 'posts#search'

  resources :administrators do
    member do
      get 'change_admin'
    end
  end

  resources :replies do
    member do
      get 'add_reply'
    end
  end

  match ':controller(/:id(/:action))'
  match ':controller/:action/:id'

  root :to => 'posts#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  # :trackable, :validatable, :rememberable, :recoverable,
  devise :database_authenticatable, :registerable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :user_code, :is_admin, :first_name, :last_name, :email, :encrypted_password, :password, :password_confirmation

  has_many :posts, :dependent => :destroy
  has_many :post_votes, :dependent => :destroy
  has_many :replies, :dependent => :destroy
  has_many :reply_votes, :dependent => :destroy

  def self.search(search)
    #search_condition = "%" + search + "%"
    #self.find(:all, :conditions => ['user_code LIKE ?', search_condition])
    if !search.nil?
      search_length = search.split.length
      return find(:all, :conditions => ['user_code LIKE ? AND user_code LIKE ? AND user_code LIKE ?',
          "%#{search.split[0]}%", "%#{search.split[1]}%", "%#{search.split[search_length]}%" ])
    else
      find(:all)
    end
  end

  validates_uniqueness_of :user_code, :scope => :id
  validates_uniqueness_of :email, :scope => :id
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :get_user, :only => [:index,:new,:edit]
  #before_filter :accessible_roles, :only => [:new, :edit, :show, :update, :create]
  #load_and_authorize_resource :only => [:show,:new,:destroy,:edit,:update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @postcount = Post.count_by_sql ["select count(id) from POSTS where user_id = ?", params[:id] ]
    @replycount = Reply.count_by_sql ["select count(id) from REPLIES where user_id = ?", params[:id] ]
    @posts = Post.find_all_by_user_id(params[:id])
    @replies = Reply.find_all_by_user_id(params[:id])
    @postvotesearned = 0
    @replyvotesearned = 0
    unless @posts.nil?
      @posts.each do |pv|
        @postvotesearned = @postvotesearned + pv.vote_count
      end
    end
    unless @replies.nil?
      @replies.each do |rv|
        @replyvotesearned += rv.vote_count
      end
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    if ( User.find_by_email(params[:user].email) || User.find_by_user_code(params[:user.user_code]) )
        format.html { redirect_to administrators_url, alert: 'Duplicate email or user name detected.' }
        format.json { render json: @user.errors, status:  :unprocessable_entity }
    else
      @user = User.new(params[:user])

      respond_to do |format|
        if @user.save
          format.html { redirect_to administrators_url, notice: 'User was successfully created.' }
          format.json { render json: administrators_url, status: :created, location: @user }
        else
          format.html { render action: "new" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to administrators_url, notice: 'User was successfully deleted.' }
      format.json { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label 'User Name' %><br />
    <%= f.text_field :user_code %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <tr>
    <th>User Name</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Email address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.user_code %></td>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <% if user_signed_in? %>
        <% if User.find(current_user.id).user_code ==  user.user_code %>
            <% unless user.user_code == 'admin' %>
                <td><%= link_to 'Edit', edit_user_path(user) %></td>
                <td><%= link_to 'Destroy', 'users/' + user.id.to_s + '/destroy', :confirm => 'Are you sure?', :method => :delete %></td>
            <% end %>
        <% end %>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<% if user_signed_in? %>
    <%= link_to 'New User', new_user_path %>
<% end %>
<%= link_to 'Return to Posts', posts_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', administrators_url %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Email address:</b>
  <%= @user.email %>
</p>
<div>
<p>
  <b>Post Count:</b>
  <%= @postcount %>
</p>

<p>
  <b>Reply Count:</b>
  <%= @replycount %>
</p>
</div>
<p>
  <b>Total Post Votes Earned:</b>
  <%= @postvotesearned %>
</p>

<p>
  <b>Total Reply Votes Earned:</b>
  <%= @replyvotesearned %>
</p>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', administrators_url %>