config/routes.rb
Backchannel::Application.routes.draw do

  devise_for :users
  resources :administrators
  resources :reply_votes
  resources :replies
  resources :post_votes
  resources :posts
  resources :users

  devise_for :users do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_out", :to => "devise/sessions#destroy"
  end

  match 'posts/vote/:id', :to => 'posts#vote'
  match 'search', :to => 'posts#search'

  resources :administrators do
    member do
      get 'change_admin'
    end
  end

  resources :replies do
    member do
      get 'add_reply'
    end
  end

  match ':controller(/:id(/:action))'
  match ':controller/:action/:id'

  root :to => 'posts#index'

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base

  belongs_to :user

  validates :user, :uniqueness => true
  validates :user, :presence => true
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  # GET /administrators
  # GET /administrators.json
   before_filter :require_admin!

  def index
    @users = User.all
    @administrators = Administrator.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @administrators }
    end
  end

  # GET /administrators/1
  # GET /administrators/1.json
  def show
    @administrator = Administrator.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @administrator }
    end
  end

  # GET /administrators/new
  # GET /administrators/new.json
  def new
    @users = User.all
    @administrator = Administrator.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @administrator }
    end
  end

  # GET /administrators/1/edit
  def edit
    @administrator = Administrator.find(params[:id])
  end

  # POST /administrators
  # POST /administrators.json
  def create
    @administrator = Administrator.new(params[:administrator])

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to @administrator, notice: 'Administrator was successfully created.' }
        format.json { render json: @administrator, status: :created, location: @administrator }
      else
        format.html { render action: "new" }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /administrators/1
  # PUT /administrators/1.json
  def update
    @administrator = Administrator.find(params[:id])

    respond_to do |format|
      if @administrator.update_attributes(params[:administrator])
        format.html { redirect_to @administrator, notice: 'Administrator was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1
  # DELETE /administrators/1.json
  def destroy
    @administrator = Administrator.find(params[:id])
    @administrator.destroy

    respond_to do |format|
      format.html { redirect_to administrators_url }
      format.json { head :ok }
    end
  end

  def change_admin
#    puts params['id'].to_s
#    puts user.user_code.to_s

    user = User.find(params['id'])
    puts user.user_code.to_s
    puts user.is_admin?.to_s + " <== Admin Status"
    if (user.is_admin?)
      user.is_admin = false
      user.save
    else
      user.is_admin = true
      user.save
    end
    respond_to do |format|
      format.html { redirect_to administrators_url, notice: 'Role succesfully changed.' }
      format.json { head :ok }
    end
  end

  protected
  def require_admin!
    unless current_user.try :is_admin?
      redirect_to root_path, :alert => "Access Denied"
    end
  end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/_form.html.erb
<%= form_for(@administrator) do |f| %>
  <% if @administrator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul>
      <% @administrator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :is_admin? %><br />
    <%= f.text_area :is_admin %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/administrators/add_admin.erb
<!-- stub html file, controller method handles redirect -->

app/views/administrators/edit.html.erb
<h1>Editing administrator</h1>

<%= render 'form' %>

<%= link_to 'Show', @administrator %> |
<%= link_to 'Back', administrators_path %>

app/views/administrators/index.html.erb
<h1>Listing Administrator Status</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

    <% #@administrators.each do |administrator| %>
    <% @users.each do |user| %>
      <tr>
        <td><b>User ID:</b>
            <%= link_to "#{user.user_code}", 'users/' + (user.id).to_s %>
            <b>Admin?:</b>
            <%= user.is_admin.to_s %>
        </td>
        <td><%= link_to 'Edit Account', edit_user_path(user.id) %></td>
        <% unless user.user_code == 'admin' %>
            <td><%= link_to 'Delete User Account', 'users/' + user.id.to_s + '/destroy', confirm: 'Are you sure?', method: :delete %></td>
        <% end %>
        <% unless user.user_code == 'admin' || current_user.id == user.id-%>
            <td><%= link_to 'Change Admin Role', :action => 'change_admin', :id => user.id %></td>
        <% end %>
      </tr>
    <% end %>
</table>

<br />

<%= link_to 'Back to Posts', posts_path %>

app/views/administrators/new.html.erb
<h1>New administrator</h1>

<%= render 'form' %>

<%= link_to 'Back', administrators_path %>

app/views/administrators/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_administrator_path(@administrator) %> |
<%= link_to 'Back', administrators_path %>