config/routes.rb
Backchannel::Application.routes.draw do

  devise_for :users
  resources :administrators
  resources :reply_votes
  resources :replies
  resources :post_votes
  resources :posts
  resources :users

  devise_for :users do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_out", :to => "devise/sessions#destroy"
  end

  match 'posts/vote/:id', :to => 'posts#vote'
  match 'search', :to => 'posts#search'

  resources :administrators do
    member do
      get 'change_admin'
    end
  end

  resources :replies do
    member do
      get 'add_reply'
    end
  end

  match ':controller(/:id(/:action))'
  match ':controller/:action/:id'

  root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :post_votes, :dependent => :destroy
  has_many :replies, :dependent => :destroy
  attr_accessible :post_text, :vote_count, :user_id
  #validates_presence_of :post_text => I18n.t('AuthenticatedUser')
  # is this a reasonable minimum of for a post
  validates_length_of :post_text, :minimum => 10, :message => I18n.t('PostTooShort')

  def self.search(search)
    #@terms = search.split(" ").map { |s| s }
    #puts @terms.to_s
    #search_condition = "%" + search + "%"
    #self.find(:all, :conditions => ['post_text LIKE ?', search_condition])
      if !search.nil?
        search_length = search.split.length
        return find(:all, :conditions => ['post_text LIKE ? AND post_text LIKE ? AND post_text LIKE ?',
          "%#{search.split[0]}%", "%#{search.split[1]}%", "%#{search.split[search_length]}%" ])
      else
        find(:all)
      end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  before_filter :authenticate_user!, :except => [:index, :show, :search]

  def index
    @posts = Post.all
    date = DateTime.now.to_date
    puts date
    puts "end of debug stuff"
    @posts.sort! { |a,b| ( b.vote_count - ( 5 * (date - b.created_at.to_date) )  <=>
                              a.vote_count - ( 5 * ( date - a.created_at.to_date ) ) ) }
    @replies = Array.new
    @posts.each do |post|
      @replies << Reply.where(:post_id => post.id)
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts, json: @replies }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    if current_user.id != @post.user_id
      redirect_to posts_path, alert:  'You may only edit your own posts.'
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.user_id = current_user.id   # Assign FK to posting for user
    # --> Do we want to assign a vote of 1 to each post initially?
    @post.vote_count = 0

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render json: posts_path, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :ok }
    end
  end

  def search
    @posts = Post.search( params[:q] )
    @replies = Reply.search( params[:q] )
    @user = User.search( params[:q] )
    @userPost = Array.new
    unless @user.nil?
      @user.each do |users|
        @userPost << Post.find_by_user_id(users.id)
      end
    end
    #puts "Posts found ==> " + @posts.to_s
    #n = "Searching for \'" + params[:q].to_s + "\'"

    respond_to do |format|
      format.html
      format.json { head :ok }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_text %><br />
    <%= f.text_area :post_text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_search.html.erb
<%= form_tag("search", :controller => "posts", :method => "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/posts/_search_results.html.erb
<ul>
   <% @posts.each do |post| %>
<li><%= link_to post.post_text,
  :action => 'show', :id => post.id  %></li>
<% end %>
</ul>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table id="table-style">
  <tr>
    <th>User Name</th>
    <th>Post Text</th>
    <th>Vote Count</th>
    <th>Created On</th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= User.find_by_id(post.user_id).user_code %></td>
    <td><%= link_to "#{post.post_text}", reply_path(post.id) %></td>
    <td><%= post.vote_count %></td>
    <td><%= post.created_at.to_date %></td>
    <% unless user_signed_in? -%>
        <% # Do Nothing %>
    <% else -%>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <% unless !user_signed_in? and !current_user.user_id == post.user_id-%>
            <td><%= link_to 'Vote', new_post_vote_path(post) %></td>
        <% end %>
        <% unless !current_user.is_admin? %>
            <td><%= link_to 'Destroy', 'posts/' + post.id.to_s + '/destroy', confirm: 'Are you sure?', :method => :delete %></td>
        <% end %>
    </tr>
    <% end %>
<% end %>
</table>

<br />
<% unless user_signed_in? -%>
  <li><%= link_to "Sign in", new_user_session_path %></li>
<% else -%>
  <li><%= link_to 'New Post', new_post_path %></li>
  <li><%= link_to "Sign out", "/sign_out", :method => :delete %></li>
<% end -%>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/search.html.erb
<li><%= link_to "Return to Posts Index", posts_path %></li>

<h1>Search Results</h1>

<h2>Results for Posts</h2>
<table id="table-style">
  <tr>
    <th>Post text</th>
    <th>Vote count</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% unless @posts.nil? %>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to "#{post.post_text}", reply_path(post.id) %></td>
        <td><%= post.vote_count %></td>
        <% unless user_signed_in? -%>
            <% # Do Nothing %>
        <% else -%>
            <% unless !user_signed_in? and !current_user.user_id == post.user_id-%>
                <td><%= link_to 'Edit', edit_post_path(post) %></td>
                <td><%= link_to 'Vote', new_post_vote_path(post) %></td>
            <% end %>
        </tr>
        <% end %>
    <% end %>
<% end %>

</table>

<h2>Results for Replies to Post</h2>

<table id="table-style">
  <tr>
    <th>Reply text</th>
    <th>Vote count</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% unless @replies.nil? %>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= link_to "#{reply.reply_text}", reply_path(reply.post_id)  %></td>
        <td><%= reply.vote_count %></td>
        <% unless user_signed_in? -%>
            <% # Do Nothing %>
        <% else -%>
            <% unless !user_signed_in? and !current_user.user_id == post.user_id-%>
                <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
                <td><%= link_to 'Vote', new_reply_vote_path(reply) %></td>
            <% end %>
        </tr>
        <% end %>
    <% end %>
<% end %>
</table>

<h2>Results by UserName</h2>

<table id="table-style">
  <tr>
    <th>Post Text</th>
    <th>Vote Count</th>
    <th>UserName</th>
    <th></th>
    <th></th>
  </tr>

  <% puts "Size" %>
<% puts @userPost.size %>
  <% puts "String Representation" %>
<% puts @userPost.to_s %>
<% puts @userPost.class %>

    <% @userPost.each do |upst| %>
      <tr>
        <% unless upst.nil? %>
            <td><%= upst.post_text  %></td>
            <td><%= upst.vote_count %></td>
            <td><%= User.find(upst.user_id).user_code %></td>
            <% unless user_signed_in? -%>
                <% # Do Nothing %>
            <% else -%>
                <% unless !user_signed_in? and !current_user.user_id == post.user_id-%>
                    <td><%= link_to 'Edit', edit_post_path(upst) %></td>
                    <td><%= link_to 'Vote', new_post_vote_path(upst) %></td>
                <% end %>
            <% end %>
        <% end %>
      </tr>
    <% end %>
</table>

<br />
<% unless user_signed_in? -%>
  <li><%= link_to "Sign in", new_user_session_path %></li>
  <li><%= link_to "Back to Posts", posts_path %></li>
<% else -%>
  <li><%= link_to 'New Post', new_post_path %></li>
  <li><%= link_to "Sign out", destroy_user_session_path %></li>
<% end %>

app/views/posts/show.html.erb
<h2>Viewing Post #<%= @post.id %> submitted by <%= User.find(@post.user_id).user_code %></h2>
<p>
  <b>Post text:</b>
  <%= @post.post_text %>
</p>

<p>
  <b>Vote count:</b>
  <%= @post.vote_count %>
  <b>Post by:</b>
  <%= User.find( @post.user_id ).user_code %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %>